name: CI
on:
  - push
  - pull_request
jobs:
  phpunit:
    name: Unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{matrix.php-version}}
          tools: composer
      - run: composer install
      - name: phpunit test
        run: vendor/bin/phpunit
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_SECRET}}
          fail_ci_if_error: true
  phpstan:
    name: phpstan analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{matrix.php-version}}
          tools: composer
      - run: composer install
      - name: phpstan analyze
        run: vendor/bin/phpstan analyze
  infection:
    name: Mutation test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{matrix.php-version}}
          tools: composer
      - run: composer install
      - name: infection
        run: vendor/bin/infection -s
      - uses: actions/upload-artifact@v1
        with:
          name: infection.log
          path: infection.log
      - uses: actions/upload-artifact@v1
        with:
          name: infection-summary.log
          path: infection-summary.log
      - uses: actions/upload-artifact@v1
        with:
          name: infection-per-mutator.md
          path: infection-per-mutator.md
